apiVersion: apps/v1
kind: Deployment
metadata:
  name: mme
  labels:
    app: mme
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mme
  template:
    metadata:
      labels:
        app: mme
    spec:
      containers:
        - name: atsi-p8
          image: clifu/atsi_p8
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf
  labels:
    app: upf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      labels:
        app: upf
    spec:
      containers:
        - name: simple-web
          image: yeasy/simple-web:latest
          ports:
            - containerPort: 80
